import { AppHeader } from "./AppHeader"
import Head from "next/head";
import { useEffect } from "react";
import { useIsLoggedInQuery } from "@/store/services/user";
import { handleNavigationCheck } from "@/utils/helpers/routes";

export const AppBody = ({page = '', className = '', children}) => {
    const { data, isLoading, isFetching, isSuccess } = useIsLoggedInQuery({
        refetchOnMountOrArgChange: 30,
        skip: false,
    });

    useEffect(() => {
        console.log('query data: ', data, isFetching, isLoading, isSuccess);
        if (data && !isFetching && !isSuccess) {
            console.log('no success: ', isFetching, isSuccess);
            handleNavigationCheck();
        }
    }, [isFetching, isLoading, isSuccess, data]);

    console.log('loading: ', page);

    return (
        <div className="app">
            <Head>
                <title>{page}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            
                <main className="App">
                    <AppHeader />

                    <div className={`app-body ${className}`}>
                        {!isFetching && children}
                    </div>
                </main>
            
        </div>
    );
}