import { AppHeader } from "./AppHeader"
import Head from "next/head";
import { useEffect } from "react";
import { useIsLoggedInMutation } from "@/store/services/user";
import { handleNavigationCheck } from "@/utils/helpers/routes";

export const AppBody = ({page = '', className = '', children}) => {
    const [handleIsLoggedIn] = useIsLoggedInMutation();

    useEffect(() => {
        const doAction = async () => await handleIsLoggedIn({}).unwrap();
        doAction();
    }, [handleIsLoggedIn]);

    console.log('loading: ', page);

    return (
        <div className="app">
            <Head>
                <title>{page}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            
                <main className="App">
                    <AppHeader />

                    <div className={`app-body ${className}`}>
                        {!isFetching && children}
                    </div>
                </main>
            
        </div>
    );
}