import { AppHeader } from "./AppHeader"
import Head from "next/head";
import { useEffect, useRef } from "react";
import { checkIfLoggedIn } from "@/utils/helpers/auth";

export const AppBody = ({page = '', children}) => {
    
    const hasConfirmed = useRef(false);

    useEffect(() => {
        if (!hasConfirmed.current) {
            checkIfLoggedIn();

            hasConfirmed.current = true;
        }
    }, []);

    return (
        <div className="app">
            <Head>
                <title>{page}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="App">
                <AppHeader />

                <div>
                    {children}
                </div>
            </main>
        </div>
    );
}