import Head from 'next/head';
import { Inter } from '@next/font/google';
import { Users } from './Users';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
    return (
        <>
            <Head>
                <title>Cool title</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
        </Head>
            <main>
                    <div style={{
                    display: 'flex',
                    justifyItems: 'center',
                    justifyContent: 'center',
                    width: '100%',
                    height: '100vh',
                    alignItems: 'center',
                    fontSize: 32,
                    }}>
                        <Users />
                    </div>
            </main>
        </>
    );
}
