import Head from 'next/head';
import { Users } from './Users';
import {FormGroup} from '@/components/FormGroup';
import { Button } from '@/components/Button';
import { useState } from 'react';
import axios from 'axios';

export default function Home() {
    interface FormDataTypes { username: '', password: '', email: ''}
    const formData: FormDataTypes = {username: '', password: '', email: ''}
    const [formDataFormatted, setFormDataFormatted] = useState<formDataTypes>(formData);

    const handleSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
        e.preventDefault();
        console.log('hello', formDataFormatted);

        await axios.post('http://localhost:8081/create', formDataFormatted).then((response) => {
            
            if (response) {
                console.log(response);
            }
        });
    };

    const formInputs = [
        {
            title: 'Brukernavn',
            name: 'username',
            type: 'text',
        },
        {
            title: 'Passord',
            name: 'password',
            type: 'password',
        },
        {
            title: 'E-post',
            name: 'email',
            type: 'email',
        },
    ];

    const inputOnChange = (event: React.ChangeEvent<HTMLInputElement>) => {
        const {name, value} = event.target
        const newData = {...formDataFormatted, [name]: value};
        console.log(newData);
        setFormDataFormatted(newData);
    }

    return (
        <>
            <Head>
                <title>Cool title</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <div className="app">
                    <Users />
                    <div className="container mt-20">
                        <form className="form bg-dark" onSubmit={(e) => handleSubmit(e)}>
                            <div className="form-title">
                                Registrer ny bruker
                            </div>
                            {formInputs.map((input, key) => (
                                <FormGroup
                                    title={input.title}
                                    name={input.name}
                                    type={input.type}
                                    key={key}
                                    inputOnChange={inputOnChange}
                                />
                            ))}

                            <FormGroup
                                title=''
                                name='submit'
                                type='submit'
                            />
                        </form>
                    </div>
                </div>
            </main>
        </>
    );
}
